events {}

http {
  include /etc/nginx/mime.types;
  sendfile on;
  server_tokens off;
  client_max_body_size 12m;
  gzip on;
  gzip_types text/plain text/css application/json application/javascript application/xml image/svg+xml;
  include /etc/nginx/conf.d/*.conf;
}
